// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvlOkK5CNyA6QVyQyUVDMv_oWo5Gn50OY',
    appId: '1:258687794093:web:7f39a371504aca80d43f24',
    messagingSenderId: '258687794093',
    projectId: 'is-project-ii-eb8ce',
    authDomain: 'is-project-ii-eb8ce.firebaseapp.com',
    storageBucket: 'is-project-ii-eb8ce.firebasestorage.app',
    measurementId: 'G-XC9684SC7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTgFRG8oSAs7QrmCN-VCz_UdV8IMq-Q9s',
    appId: '1:258687794093:android:cea2476377006ebfd43f24',
    messagingSenderId: '258687794093',
    projectId: 'is-project-ii-eb8ce',
    storageBucket: 'is-project-ii-eb8ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnDFt9ORYyZHrw24un3n-Y8sCQuxGS_54',
    appId: '1:258687794093:ios:9cac995424399856d43f24',
    messagingSenderId: '258687794093',
    projectId: 'is-project-ii-eb8ce',
    storageBucket: 'is-project-ii-eb8ce.firebasestorage.app',
    iosBundleId: 'com.example.isApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnDFt9ORYyZHrw24un3n-Y8sCQuxGS_54',
    appId: '1:258687794093:ios:9cac995424399856d43f24',
    messagingSenderId: '258687794093',
    projectId: 'is-project-ii-eb8ce',
    storageBucket: 'is-project-ii-eb8ce.firebasestorage.app',
    iosBundleId: 'com.example.isApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvlOkK5CNyA6QVyQyUVDMv_oWo5Gn50OY',
    appId: '1:258687794093:web:e75c096814096750d43f24',
    messagingSenderId: '258687794093',
    projectId: 'is-project-ii-eb8ce',
    authDomain: 'is-project-ii-eb8ce.firebaseapp.com',
    storageBucket: 'is-project-ii-eb8ce.firebasestorage.app',
    measurementId: 'G-97J9TR3JXY',
  );
}
