// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzJuBQRsGSFnsiRnayeUyOHYQjoGYBrSg',
    appId: '1:584543486775:web:e7320a21f2ecdca1efd0b2',
    messagingSenderId: '584543486775',
    projectId: 'is-project-ii-b8e35',
    authDomain: 'is-project-ii-b8e35.firebaseapp.com',
    storageBucket: 'is-project-ii-b8e35.firebasestorage.app',
    measurementId: 'G-W6N60C02W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHS4XeR2HqlX5u5Ynir87gVi3yx-XEyG8',
    appId: '1:584543486775:android:6334a4639cfb0646efd0b2',
    messagingSenderId: '584543486775',
    projectId: 'is-project-ii-b8e35',
    storageBucket: 'is-project-ii-b8e35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ZJneQPdAGelju0fN850dujJihGHC5X8',
    appId: '1:584543486775:ios:a0a445370242b337efd0b2',
    messagingSenderId: '584543486775',
    projectId: 'is-project-ii-b8e35',
    storageBucket: 'is-project-ii-b8e35.firebasestorage.app',
    iosBundleId: 'com.example.icsApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ZJneQPdAGelju0fN850dujJihGHC5X8',
    appId: '1:584543486775:ios:a0a445370242b337efd0b2',
    messagingSenderId: '584543486775',
    projectId: 'is-project-ii-b8e35',
    storageBucket: 'is-project-ii-b8e35.firebasestorage.app',
    iosBundleId: 'com.example.icsApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzJuBQRsGSFnsiRnayeUyOHYQjoGYBrSg',
    appId: '1:584543486775:web:0accee1813d7263cefd0b2',
    messagingSenderId: '584543486775',
    projectId: 'is-project-ii-b8e35',
    authDomain: 'is-project-ii-b8e35.firebaseapp.com',
    storageBucket: 'is-project-ii-b8e35.firebasestorage.app',
    measurementId: 'G-T9SKDLZ0CV',
  );
}
